POST http://{{host}}:{{port}}/tcpProxy/createProxy
Accept: application/json
Content-Type: application/json

{
  "proxyName":"HelloWorld",
  "localPort": 9000,
  "proxyTargetEndPoint": [
      {
        "targetPort": 80,
        "targetAddress": "www.6park.com"
      }
    ],
  "workerCount": 3
}